### ISSUE TITLE
Update for Django 3.x?

### ISSUE THREAD

**Issue by myers** [artofhuman/django-pg-upsert#16]
Could this be updated for Django 3.2?

ps - is  djnago_settings.py meant to be misspelled?

**Comment by artofhuman** [comment]
@myers Hi, I added tests for 3.2 https://github.com/artofhuman/django-pg-upsert/pull/17 it looks like all works for Django 3.2. Can you describe your problem with 3.2?

**Comment by artofhuman** [comment]
@myers Thanks. I realized new version 0.2.0 for django 3.x
